version:  '3.1'
services:
  app:
    container_name: blog-api
    image: blog-api
    build: ./
    ports:
      - "9093:9092"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=lombab56
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blogApi
